In [2]:
import pandas as pd
import numpy as np

1. Import des fchiers CSV

    1.1 Table filtrée

In [3]:
movies_final = pd.read_csv("C:/Users/karelle/OneDrive/Documents/Projet 2/Base de données/fichiers csv/version 2/tabMovieRatingGenreFiltre.csv", sep = ';', index_col = 0)
movies_final

,title,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,Action,Adult,...,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western,decade
6389,Kate et Léopold,tt0035423,Kate & Leopold,2001,118,"Comedy,Fantasy,Romance",6.4,83389,0,0,...,0,1,0,0,0,0,0,0,0,2000
17197,L'éveil de la bête,tt0062690,Awakening of the Beast,1970,93,"Drama,Horror",5.9,1157,0,0,...,0,0,0,0,0,0,0,0,0,1970
17804,Le boucher,tt0064106,Le Boucher,1970,93,"Drama,Thriller",7.4,8535,0,0,...,0,0,0,0,0,0,1,0,0,1970
17839,Les choses de la vie,tt0064165,The Things of Life,1970,89,"Drama,Romance",7.5,4767,0,0,...,0,1,0,0,0,0,0,0,0,1970
17852,Le cerveau d'acier,tt0064177,Colossus: The Forbin Project,1970,100,"Sci-Fi,Thriller",7.1,8878,0,0,...,0,0,1,0,0,0,1,0,0,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112052,Eight for Silver,tt9907782,The Cursed,2021,111,"Fantasy,Horror,Mystery",6.3,4382,0,0,...,0,0,0,0,0,0,0,0,0,2020
112053,Le lion,tt9908390,Le lion,2020,95,Comedy,5.4,1063,0,0,...,0,0,0,0,0,0,0,0,0,2020
112055,Zalim Istanbul,tt9910728,Zalim Istanbul,2019,120,Drama,6.1,860,0,0,...,0,0,0,0,0,0,0,0,0,2010
112057,De Beentjes van Sint-Hildegard,tt9911196,The Marriage Escape,2020,103,"Comedy,Drama",7.5,3551,0,0,...,0,0,0,0,0,0,0,0,0,2020
112065,Les sorcières d'Akelarre,tt9916362,Coven,2020,92,"Drama,History",6.4,4520,0,0,...,0,0,0,0,0,0,0,0,0,2020

    1.2 Table réalisateurs

In [4]:
best_director = pd.read_csv("C:/Users/karelle/OneDrive/Documents/Projet 2/Base de données/fichiers csv/version 2/tab_best_director.csv", sep = ';', index_col = 0)
best_director

       directors     tconst  primaryName
0      nm0000095  tt0065063  Woody Allen
1      nm0000095  tt0066808  Woody Allen
2      nm0000095  tt0068555  Woody Allen
3      nm0000095  tt0070707  Woody Allen
4      nm0000095  tt0073312  Woody Allen
...          ...        ...          ...
14448  nm0003418  tt2406560    Rob Cohen
14449  nm0003418  tt3181822    Rob Cohen
14450  nm0003418  tt3650286    Rob Cohen
14451  nm0003418  tt5360952    Rob Cohen
14452  nm0003418  tt6743490    Rob Cohen

[14453 rows x 3 columns]

    1.3 Table du pays d'origine des films

In [10]:
language = pd.read_csv("C:/Users/karelle/OneDrive/Documents/Projet 2/Base de données/fichiers csv/version 2/movies_metadata.csv", sep =',', usecols= ['imdb_id','original_language'])
language = language.dropna()
language.head(5)

     imdb_id original_language
0  tt0114709                en
1  tt0113497                en
2  tt0113228                en
3  tt0114885                en
4  tt0113041                en

2. Jointure

In [7]:
tab_movies_director = pd.merge(movies_final,best_director, how = "left", left_on = "tconst", right_on = "tconst")
tab_movies_director = tab_movies_director.fillna(0)
tab_movies_director

,title,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,Action,Adult,...,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western,decade,directors,primaryName
0,Kate et Léopold,tt0035423,Kate & Leopold,2001,118,"Comedy,Fantasy,Romance",6.4,83389,0,0,...,0,0,0,0,0,0,0,2000,0,0
1,L'éveil de la bête,tt0062690,Awakening of the Beast,1970,93,"Drama,Horror",5.9,1157,0,0,...,0,0,0,0,0,0,0,1970,0,0
2,Le boucher,tt0064106,Le Boucher,1970,93,"Drama,Thriller",7.4,8535,0,0,...,0,0,0,0,1,0,0,1970,nm0001031,Claude Chabrol
3,Les choses de la vie,tt0064165,The Things of Life,1970,89,"Drama,Romance",7.5,4767,0,0,...,0,0,0,0,0,0,0,1970,nm0767110,Claude Sautet
4,Le cerveau d'acier,tt0064177,Colossus: The Forbin Project,1970,100,"Sci-Fi,Thriller",7.1,8878,0,0,...,1,0,0,0,1,0,0,1970,nm0765121,Joseph Sargent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26029,Eight for Silver,tt9907782,The Cursed,2021,111,"Fantasy,Horror,Mystery",6.3,4382,0,0,...,0,0,0,0,0,0,0,2020,0,0
26030,Le lion,tt9908390,Le lion,2020,95,Comedy,5.4,1063,0,0,...,0,0,0,0,0,0,0,2020,0,0
26031,Zalim Istanbul,tt9910728,Zalim Istanbul,2019,120,Drama,6.1,860,0,0,...,0,0,0,0,0,0,0,2010,0,0
26032,De Beentjes van Sint-Hildegard,tt9911196,The Marriage Escape,2020,103,"Comedy,Drama",7.5,3551,0,0,...,0,0,0,0,0,0,0,2020,0,0
26033,Les sorcières d'Akelarre,tt9916362,Coven,2020,92,"Drama,History",6.4,4520,0,0,...,0,0,0,0,0,0,0,2020,0,0

In [14]:
tab_movies_director= pd.get_dummies(data = tab_movies_director,columns = ['primaryName'], prefix = "", sparse = True)
tab_movies_director

,title,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,Action,Adult,...,_Wes Craven,_William Friedkin,_Wilson Yip,_Wim Wenders,_Wolfgang Petersen,_Woo-Ping Yuen,_Woody Allen,_Yimou Zhang,_Álex de la Iglesia,_Éric Rohmer
0,Kate et Léopold,tt0035423,Kate & Leopold,2001,118,"Comedy,Fantasy,Romance",6.4,83389,0,0,...,0,0,0,0,0,0,0,0,0,0
1,L'éveil de la bête,tt0062690,Awakening of the Beast,1970,93,"Drama,Horror",5.9,1157,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Le boucher,tt0064106,Le Boucher,1970,93,"Drama,Thriller",7.4,8535,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Les choses de la vie,tt0064165,The Things of Life,1970,89,"Drama,Romance",7.5,4767,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Le cerveau d'acier,tt0064177,Colossus: The Forbin Project,1970,100,"Sci-Fi,Thriller",7.1,8878,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26029,Eight for Silver,tt9907782,The Cursed,2021,111,"Fantasy,Horror,Mystery",6.3,4382,0,0,...,0,0,0,0,0,0,0,0,0,0
26030,Le lion,tt9908390,Le lion,2020,95,Comedy,5.4,1063,0,0,...,0,0,0,0,0,0,0,0,0,0
26031,Zalim Istanbul,tt9910728,Zalim Istanbul,2019,120,Drama,6.1,860,0,0,...,0,0,0,0,0,0,0,0,0,0
26032,De Beentjes van Sint-Hildegard,tt9911196,The Marriage Escape,2020,103,"Comedy,Drama",7.5,3551,0,0,...,0,0,0,0,0,0,0,0,0,0
26033,Les sorcières d'Akelarre,tt9916362,Coven,2020,92,"Drama,History",6.4,4520,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
tab_genre_dir_lang = pd.merge(tab_movies_director,language, how = "left", left_on = "tconst", right_on = "imdb_id").drop(columns = "imdb_id")
tab_genre_dir_lang = tab_genre_dir_lang.fillna(0)
tab_genre_dir_lang.head(5)

,title,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,Action,Adult,...,_William Friedkin,_Wilson Yip,_Wim Wenders,_Wolfgang Petersen,_Woo-Ping Yuen,_Woody Allen,_Yimou Zhang,_Álex de la Iglesia,_Éric Rohmer,original_language
0,Kate et Léopold,tt0035423,Kate & Leopold,2001,118,"Comedy,Fantasy,Romance",6.4,83389,0,0,...,0,0,0,0,0,0,0,0,0,en
1,L'éveil de la bête,tt0062690,Awakening of the Beast,1970,93,"Drama,Horror",5.9,1157,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Le boucher,tt0064106,Le Boucher,1970,93,"Drama,Thriller",7.4,8535,0,0,...,0,0,0,0,0,0,0,0,0,fr
3,Les choses de la vie,tt0064165,The Things of Life,1970,89,"Drama,Romance",7.5,4767,0,0,...,0,0,0,0,0,0,0,0,0,fr
4,Le cerveau d'acier,tt0064177,Colossus: The Forbin Project,1970,100,"Sci-Fi,Thriller",7.1,8878,0,0,...,0,0,0,0,0,0,0,0,0,en

In [17]:
tab_genre_dir_lang= pd.get_dummies(data = tab_genre_dir_lang,columns = ['original_language'], prefix = "", sparse = True)
tab_genre_dir_lang.head(5)

,title,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,Action,Adult,...,_th,_tl,_tr,_uk,_ur,_vi,_wo,_xx,_zh,_zu
0,Kate et Léopold,tt0035423,Kate & Leopold,2001,118,"Comedy,Fantasy,Romance",6.4,83389,0,0,...,0,0,0,0,0,0,0,0,0,0
1,L'éveil de la bête,tt0062690,Awakening of the Beast,1970,93,"Drama,Horror",5.9,1157,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Le boucher,tt0064106,Le Boucher,1970,93,"Drama,Thriller",7.4,8535,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Les choses de la vie,tt0064165,The Things of Life,1970,89,"Drama,Romance",7.5,4767,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Le cerveau d'acier,tt0064177,Colossus: The Forbin Project,1970,100,"Sci-Fi,Thriller",7.1,8878,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
table_KNN = tab_genre_dir_lang.drop(columns = "_0")
table_KNN.drop_duplicates()
table_KNN

,title,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,Action,Adult,...,_th,_tl,_tr,_uk,_ur,_vi,_wo,_xx,_zh,_zu
0,Kate et Léopold,tt0035423,Kate & Leopold,2001,118,"Comedy,Fantasy,Romance",6.4,83389,0,0,...,0,0,0,0,0,0,0,0,0,0
1,L'éveil de la bête,tt0062690,Awakening of the Beast,1970,93,"Drama,Horror",5.9,1157,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Le boucher,tt0064106,Le Boucher,1970,93,"Drama,Thriller",7.4,8535,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Les choses de la vie,tt0064165,The Things of Life,1970,89,"Drama,Romance",7.5,4767,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Le cerveau d'acier,tt0064177,Colossus: The Forbin Project,1970,100,"Sci-Fi,Thriller",7.1,8878,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26048,Eight for Silver,tt9907782,The Cursed,2021,111,"Fantasy,Horror,Mystery",6.3,4382,0,0,...,0,0,0,0,0,0,0,0,0,0
26049,Le lion,tt9908390,Le lion,2020,95,Comedy,5.4,1063,0,0,...,0,0,0,0,0,0,0,0,0,0
26050,Zalim Istanbul,tt9910728,Zalim Istanbul,2019,120,Drama,6.1,860,0,0,...,0,0,0,0,0,0,0,0,0,0
26051,De Beentjes van Sint-Hildegard,tt9911196,The Marriage Escape,2020,103,"Comedy,Drama",7.5,3551,0,0,...,0,0,0,0,0,0,0,0,0,0
26052,Les sorcières d'Akelarre,tt9916362,Coven,2020,92,"Drama,History",6.4,4520,0,0,...,0,0,0,0,0,0,0,0,0,0

3. Export fichier CSV

In [19]:
table_KNN.to_csv("table_KNN.csv",sep = ";")